# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Build and deploy Python app to Azure Web App - socialkart

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
      
      - name: Install dependencies
        # --- CHANGE 1: Specify the path to requirements.txt within the 'backend' folder ---
        run: pip install -r backend/requirements.txt
        
      # Optional: Add step to run tests here (PyTest, Django test suites, etc.)

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          # --- CHANGE 2: Specify that ONLY the 'backend' directory should be uploaded as the artifact ---
          # This ensures that when the artifact is deployed, 'app.py' and 'requirements.txt' are at the root
          # of the deployed content on Azure.
          path: backend/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app
      
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_BF799EB9A5344308B7CC35552B53922E }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_F910F82BD38D45B7AB495CD23E302632 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_1EB14B4E2BB144E99F2973EF75914351 }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'socialkart'
          slot-name: 'Production'
          # --- CHANGE 3: Specify that the deployed package is the current directory (which contains the backend content) ---
          package: '.'